### ISSUE TITLE
Better error message for "Invalid prefix H"

### ISSUE THREAD

**Issue by madsrasmussen** [umbraco/Umbraco.Cloud.Issues#113]
When deploying a content node I get this error message. I have really no clue how to proceed.

![image](https://user-images.githubusercontent.com/6078361/63838072-ef558e00-c97c-11e9-9a88-c391117763c7.png)

```
ed0eac3d - Executing, 10% - Get remote session
ed0eac3d - Executing, 20% - Create manifest on source
❤
ed0eac3d - Executing, 25% - Review manifest on target
ed0eac3d - Executing, 28% - Negotiate files transfer.
ed0eac3d - Executing, 30% - Create package on source
ed0eac3d - Executing, 30% - Complete local session
ed0eac3d - Executing, 35% - Process package on target
❤
ed0eac3d - Executing, 80% - Exception!
ed0eac3d - Executing, 80% - Abort remote session
ed0eac3d - Failed, 80% - Total time 00:00:09.587.
-- EXCEPTION ---------------------------------------------------
 (proper exception traces at the end of this log)
System.NotSupportedException: Invalid prefix 'S'.
Umbraco.Deploy.Exceptions.ProcessArtifactException: Process pass #4 failed for artifact umb://document/7799c2b61c1845f18a5faa347d632aab.
 On: <umb://document/7799c2b61c1845f18a5faa347d632aab>
Umbraco.Deploy.Exceptions.RemoteApiException: The remote API has thrown an exception.
-- UDIS --------------------------------------------------------
<umb://document/7799c2b61c1845f18a5faa347d632aab>
----------------------------------------------------------------
EXCEPTION:
Umbraco.Deploy.Exceptions.RemoteApiException: The remote API has thrown an exception.
   at Umbraco.Deploy.Environments.RemoteUmbracoEnvironment.<SucceedOrThrow>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.Environments.RemoteUmbracoEnvironment.<WaitAction>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.Environments.RemoteUmbracoEnvironment.<ProcessPackageAsync>d__40.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.WorkItems.DeployRestoreWorkItemBase.<ProcessPackage>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.WorkItems.SourceDeployWorkItem.<ExecuteAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Umbraco.Deploy.WorkItems.SourceDeployWorkItem.<ExecuteAsync>d__15.MoveNext()
REMOTE:
Umbraco.Deploy.Exceptions.ProcessArtifactException: Process pass #4 failed for artifact umb://document/7799c2b61c1845f18a5faa347d632aab.
   at Umbraco.Deploy.Environments.LocalUmbracoEnvironment.ProcessArtifacts(IEnumerable`1 arts, IDeployContext context, CancellationToken token)
   at Umbraco.Deploy.Environments.LocalUmbracoEnvironment.ProcessPackageAsync(Guid sessionId, Package package, CancellationToken token)
   at Umbraco.Deploy.Environments.EnvironmentController.<>c__DisplayClass16_0.<<BeginProcessPackage>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.WorkItems.SessionWorkItem.<ExecuteAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Umbraco.Deploy.WorkItems.SessionWorkItem.WaitIdle()
   at Umbraco.Deploy.Environments.EnvironmentController.WaitIdle(SessionActionModel model)
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
--> System.NotSupportedException: Invalid prefix 'S'.
   at Umbraco.Deploy.ValueConnectors.DefaultValueConnector.SetValue(IContentBase content, String alias, String value)
   at Umbraco.Deploy.Contrib.Connectors.ValueConnectors.NestedContentValueConnector.SetValue(IContentBase content, String alias, String value)
   at Umbraco.Deploy.ServiceConnectors.ContentConnectorBase`2.MapProperties(TContent content, IEnumerable`1 propertyTypes, IDictionary`2 artProperties)
   at Umbraco.Deploy.ServiceConnectors.DocumentConnector.Process4(DeployState state, IDeployContext context, Int32 pass)
   at Umbraco.Deploy.ServiceConnectors.DocumentConnector.Process(ArtifactDeployState`2 state, IDeployContext context, Int32 pass)
   at Umbraco.Deploy.ServiceConnectors.ServiceConnectorBase`3.Process(ArtifactDeployState dart, IDeployContext context, Int32 pass)
   at Umbraco.Deploy.Environments.LocalUmbracoEnvironment.ProcessArtifacts(IEnumerable`1 arts, IDeployContext context, CancellationToken token)
```

**Comment by jmayntzhusen** [comment]
This has been fixed from Deploy 3.3.0 - https://github.com/umbraco/Umbraco-Deploy/commit/2faaeee11436f2748d57a22b71ccd421d8b9e026

It is both less likely to hit the error now, and the error message has been changed to make it clearer what is happening / where the issue is.

Thanks for reporting the issue!
