### ISSUE TITLE
Failure during UmbracoForms prevalue source deployment

### ISSUE THREAD

**Issue by idseefeld** [umbraco/Umbraco.Cloud.Issues#194]
I tried to deploy a prevalue source from the Forms section to Umbraco Cloud and got an error.
Using Umbraco version 8.6.0, Forms version 8.4.0 and Deploy version 3.4.2

What I did:

1. I have created a drop-down data type in _Settings_ section.
2. Added a _Prevalue Source_ in _Forms_ section based on this data type.
3. Queued the new prevalue source.
4. Clicked _Send changes to the Development workspace_ button on Content section dashboard.
5. Deployment failed.

These are the technical details of the failure:

```
f8dfb9f1 - Executing, 10%
f8dfb9f1 - Executing, 10% - Get remote session
f8dfb9f1 - Executing, 20% - Create manifest on source
f8dfb9f1 - Executing, 25% - Review manifest on target
f8dfb9f1 - Executing, 28% - Negotiate files transfer.
f8dfb9f1 - Executing, 30% - Create package on source
f8dfb9f1 - Executing, 32% - Transfer 0 files.
f8dfb9f1 - Executing, 32% - Complete local session
f8dfb9f1 - Executing, 35% - Process package on target
f8dfb9f1 - Executing, 80% - Exception!
f8dfb9f1 - Executing, 80% - Abort remote session
f8dfb9f1 - Failed, 80% - Total time 00:00:01.824.

-- EXCEPTION ---------------------------------------------------
 (proper exception traces at the end of this log)
System.InvalidOperationException: Don't know how to map Umbraco.Deploy.Forms.Artifacts.PreValueSourceArtifact to Umbraco.Forms.Core.FieldPreValueSource.
Umbraco.Deploy.Exceptions.ProcessArtifactException: ProcessInit failed for artifact umb://forms-prevalue/feea6b94324f4295800fc9db2f557c63.
 On: <umb://forms-prevalue/feea6b94324f4295800fc9db2f557c63>
Umbraco.Deploy.Exceptions.RemoteApiException: The remote API has thrown an exception.
-- UDIS --------------------------------------------------------
<umb://forms-prevalue/feea6b94324f4295800fc9db2f557c63>
----------------------------------------------------------------

EXCEPTION:

Umbraco.Deploy.Exceptions.RemoteApiException: The remote API has thrown an exception.
   at Umbraco.Deploy.Environments.RemoteUmbracoEnvironment.<SucceedOrThrow>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Umbraco.Deploy.Environments.RemoteUmbracoEnvironment.<WaitAction>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.Environments.RemoteUmbracoEnvironment.<ProcessPackageAsync>d__43.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.Work.WorkItems.DeployRestoreWorkItemBase.<ProcessPackage>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.Work.WorkItems.SourceDeployWorkItem.<ExecuteAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Umbraco.Deploy.Work.WorkItems.SourceDeployWorkItem.<ExecuteAsync>d__15.MoveNext()

REMOTE:
Umbraco.Deploy.Exceptions.ProcessArtifactException: ProcessInit failed for artifact umb://forms-prevalue/feea6b94324f4295800fc9db2f557c63.

   at Umbraco.Deploy.Environments.CurrentEnvironment.<>c__DisplayClass22_0.<ProcessArtifacts>b__0(IArtifact x)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Umbraco.Deploy.Environments.CurrentEnvironment.ProcessArtifacts(IEnumerable`1 arts, IDeployContext context, CancellationToken token)
   at Umbraco.Deploy.Environments.CurrentEnvironment.ProcessPackageAsync(Guid sessionId, Package package, CancellationToken token)
   at Umbraco.Deploy.Environments.EnvironmentController.<>c__DisplayClass13_0.<<BeginProcessPackage>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.Work.WorkItems.SessionWorkItem.<ExecuteAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Umbraco.Deploy.Work.WorkItems.SessionWorkItem.WaitIdle()
   at Umbraco.Deploy.Environments.EnvironmentController.WaitIdle(SessionActionModel model)
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_2.<GetExecutor>b__2(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext()
--> System.InvalidOperationException: Don't know how to map Umbraco.Deploy.Forms.Artifacts.PreValueSourceArtifact to Umbraco.Forms.Core.FieldPreValueSource.

   at Umbraco.Core.Mapping.UmbracoMapper.Map[TSource,TTarget](TSource source, TTarget target, MapperContext context)
   at Umbraco.Deploy.Forms.ServiceConnectors.PreValueSourceConnector.ProcessInit(PreValueSourceArtifact art, IDeployContext context)
   at Umbraco.Deploy.Connectors.ServiceConnectors.ServiceConnectorBase`3.ProcessInit(IArtifact art, IDeployContext context)
   at Umbraco.Deploy.Environments.CurrentEnvironment.<>c__DisplayClass22_0.<ProcessArtifacts>b__0(IArtifact x)

```
I have already posted this in the forms issues https://github.com/umbraco/Umbraco.Forms.Issues/issues/337, but Tim thinks it is a deploy issue.

Yours
Dirk

**Comment by drbldgtl** [comment]
Is there an expected release date for a fix for this?

**Comment by ronaldbarendse** [comment]
As a temporary work-around, the Forms pre-values can be excluded from deployment and manually updated per environment using the following `UmbracoDeploy.Settings.config`:

```xml
<?xml version="1.0" encoding="utf-8"?>
<settings>
	<excludedEntityTypes>
		<add type="forms-prevalue" />
	</excludedEntityTypes>
	<forms transferFormsAsContent="true" />
</settings>
```

Looking at the stack trace, the `PreValueSourceConnector` tries to use `UmbracoMapper` to map the `PreValueSourceArtifact` to a `FieldPreValueSource`, but that mapping doesn't exist!

**Comment by hartviglarsen** [comment]
Any update on this?

**Comment by MagnusWL** [comment]
Upgrading to Forms 8.5.3 & Deploy 3.5.1 fixed this problem for me.
