### ISSUE TITLE
Send changes to the Live workspace: Value "[ "222" ]" of type "System.String" could not be converted to type "System.Int32" which is expected by property type "verticalAlignment"

### ISSUE THREAD

**Issue by tormnator** [umbraco/Umbraco.Cloud.Issues#242]
I'm unable to transfer a page from Dev to Live. After troubleshooting all day I still not able to fix or work around the problem. It almost seems like the underlying code is trying to convert a an array of string (with one item) to a single integer. I've studied the json code containing the grid layout and everything seems to be fine. I have created a test page with the same property editor and transferred similar data from Local via Dev to Live and that works as well.

The page contains a Grid Layout using Doc Type Grid Editor (DTGE). The DTGE uses a document type which itself uses Nested Content. The content item(s) has a property of type RadioButtonList with 3 possible values ("Top", "Center", and "Bottom"). The "222" in the error message corresponds to the "Top" value.

Everything has been working fine until just now, but it probably has been quite some time since this page was last transfered to Live. We are on Umbraco 7.15.5 and Deploy 2.1.1 and Umbraco Cloud. Maybe a regression during the latest Deploy update?

![image](https://user-images.githubusercontent.com/15617453/90834039-8cd06d00-e306-11ea-97ab-7d9f09b45332.png)

76b6ac6d - Executing, 10% - Get remote session
76b6ac6d - Executing, 20% - Create manifest on source
❤
❤
❤
❤
❤
❤
76b6ac6d - Executing, 25% - Review manifest on target
76b6ac6d - Executing, 28% - Negotiate files transfer.
76b6ac6d - Executing, 30% - Create package on source
76b6ac6d - Executing, 30% - Complete local session
76b6ac6d - Executing, 35% - Process package on target
❤
76b6ac6d - Executing, 80% - Exception!
76b6ac6d - Executing, 80% - Abort remote session
76b6ac6d - Failed, 80% - Total time 00:00:30.259.

-- EXCEPTION ---------------------------------------------------
 (proper exception traces at the end of this log)
System.InvalidOperationException: Value "[
  "222"
]" of type "System.String" could not be converted to type "System.Int32" which is expected by property type "verticalAlignment".
Umbraco.Deploy.Exceptions.ProcessArtifactException: Process pass #4 failed for artifact umb://document/18d6daf9632b41b0865e2c0295b48e33.
 On: <umb://document/18d6daf9632b41b0865e2c0295b48e33>
Umbraco.Deploy.Exceptions.RemoteApiException: The remote API has thrown an exception.
-- UDIS --------------------------------------------------------
<umb://document/18d6daf9632b41b0865e2c0295b48e33>
----------------------------------------------------------------

EXCEPTION:

Umbraco.Deploy.Exceptions.RemoteApiException: The remote API has thrown an exception.
   at Umbraco.Deploy.Environments.RemoteUmbracoEnvironment.<SucceedOrThrow>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.Environments.RemoteUmbracoEnvironment.<WaitAction>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.Environments.RemoteUmbracoEnvironment.<ProcessPackageAsync>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.WorkItems.DeployRestoreWorkItemBase.<ProcessPackage>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.WorkItems.SourceDeployWorkItem.<ExecuteAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Umbraco.Deploy.WorkItems.SourceDeployWorkItem.<ExecuteAsync>d__15.MoveNext()

REMOTE:
Umbraco.Deploy.Exceptions.ProcessArtifactException: Process pass #4 failed for artifact umb://document/18d6daf9632b41b0865e2c0295b48e33.

   at Umbraco.Deploy.Environments.LocalUmbracoEnvironment.ProcessArtifacts(IEnumerable`1 arts, IDeployContext context, CancellationToken token)
   at Umbraco.Deploy.Environments.LocalUmbracoEnvironment.ProcessPackageAsync(Guid sessionId, Package package, CancellationToken token)
   at Umbraco.Deploy.Environments.EnvironmentController.<>c__DisplayClass16_0.<<BeginProcessPackage>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.WorkItems.SessionWorkItem.<ExecuteAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Umbraco.Deploy.WorkItems.SessionWorkItem.WaitIdle()
   at Umbraco.Deploy.Environments.EnvironmentController.WaitIdle(SessionActionModel model)
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_2.<GetExecutor>b__2(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext()
--> System.InvalidOperationException: Value "[
  "222"
]" of type "System.String" could not be converted to type "System.Int32" which is expected by property type "verticalAlignment".

   at Umbraco.Core.Models.Property.ThrowTypeException(Object value, Type expected, String alias)
   at Umbraco.Core.Models.Property.set_Value(Object value)
   at Umbraco.Core.Models.ContentBase.SetValueOnProperty(String propertyTypeAlias, Object value)
   at Umbraco.Core.Models.ContentBase.SetPropertyValue(String propertyTypeAlias, String value)
   at CallSite.Target(Closure , CallSite , Object , String , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at CallSite.Target(Closure , CallSite , Object , String , Object )
   at Umbraco.Core.Models.ContentBase.SetValue(String propertyTypeAlias, Object value)
   at Umbraco.Deploy.ValueConnectors.PrevalueValueConnector.SetValue(IContentBase content, String alias, String value)
   at Umbraco.Deploy.Contrib.Connectors.GridCellValueConnectors.DocTypeGridEditorCellValueConnector.SetValue(GridControl control, Property property)
   at Umbraco.Deploy.ValueConnectors.GridValueConnector.SetValue(IContentBase content, String alias, String value)
   at Umbraco.Deploy.ServiceConnectors.ContentConnectorBase`2.MapProperties(TContent content, IEnumerable`1 propertyTypes, IDictionary`2 artProperties)
   at Umbraco.Deploy.ServiceConnectors.DocumentConnector.Process4(DeployState state, IDeployContext context, Int32 pass)
   at Umbraco.Deploy.ServiceConnectors.DocumentConnector.Process(ArtifactDeployState`2 state, IDeployContext context, Int32 pass)
   at Umbraco.Deploy.ServiceConnectors.ServiceConnectorBase`3.Process(ArtifactDeployState dart, IDeployContext context, Int32 pass)
   at Umbraco.Deploy.Environments.LocalUmbracoEnvironment.ProcessArtifacts(IEnumerable`1 arts, IDeployContext context, CancellationToken token)

**Comment by c9mbundy** [comment]
Is there any progress on this? 

All of my v7 sites use DTGE extensively and not being able to Restore local from cloud or Transfer from local to cloud, is causing me problems in maintaining sites.

Previously, there was no problem, and it would seem that something has been changed which breaks the use of DTGE with Deploy.

This issue appears to be related to changes in Deploy, either in the last update of 2.1.1 or the previous partial update to Deploy that was rolled out with 7.15.4, and I've been struggling with it ever since.

**Comment by c9mbundy** [comment]
@nul800sebastiaan  At the risk of being a pest, is there any advance on this?

Not being able to deploy from Local to Cloud or restore from Cloud to Local, is causing me a deal of pain.

All of my sites use the well known DTGE plugin, and this all used to work prior to a recent change to Deploy-2.

**Comment by c9mbundy** [comment]
Just ran into this issue again, where I was forced to deploy broken site updates from local to cloud, and then 'fix' the cloud site by adding and configuring missing DTGE doctypes in the various grids. The cloud site was broken for about an hour while this happened, but there was no alternative as I can no longer deploy content if it makes use of DTGE. Clearly, this would seem to be a JSON parsing error introduced into Deploy 2.1.x but given that Deploy is a closed project, it's hard to track down exactly what changed to cause it.

**Comment by c9mbundy** [comment]
I ran into this issue again trying to deploy updates to an existing site, and was forced to remove DTGE wrapped doctypes from grids before the deploy would complete, and then re-install and re-configure those doctypes after deployment... costing me a bunch of time and stress as the site was broken while I did this.

This is really frustrating, as prior to the last updates of Deploy-2 this all worked as expected, but after those changes were made, any deployment involving DTGE wrapped doctypes that contain lists or collections, always results in a failure. 

Obviously, a JSON parsing/encoding error would start favorite, but I have no idea how to pinpoint the problem in deploy - although presumably a git diff will provide clues as to what was changed and may be the cause.

**Comment by c9mbundy** [comment]
I just tried this with deploy 2.1.2 and it's still broken.

Deploying grids containing DocType Grid Editors (DTGE) worked fine up to deploy 2.1.0 and then a breaking change was introduced causing deployments to fail.

This is most likely a JSON parsing error, as it typically happens when the DocType of the DTGE uses and Array or Enumerable.

```
9a63f3fb - Executing, 10% - Get remote session
9a63f3fb - Executing, 20% - Create manifest on source
9a63f3fb - Executing, 25% - Review manifest on target
9a63f3fb - Executing, 30% - Create package on source
9a63f3fb - Executing, 80% - Complete remote session
9a63f3fb - Executing, 80% - Process package on target
9a63f3fb - Executing, 80% - Exception!
9a63f3fb - Executing, 80% - Abort remote session
9a63f3fb - Executing, 80% - Restore caches and indexes
9a63f3fb - Failed, 80% - Total time 00:08:09.803.

-- EXCEPTION ---------------------------------------------------
 (proper exception traces at the end of this log)
System.NotSupportedException: Invalid prefix 'u', when trying to parse 'umb://document/0e07c7f2d3eb46cb9fffd8455bcad5e5'.
Umbraco.Deploy.Exceptions.ProcessArtifactException: Process pass #4 failed for artifact umb://document/0ae61447351043cdb70381dfbf11fa07.
----------------------------------------------------------------
```

**Comment by c9mbundy** [comment]
@nul800sebastiaan - This is a deploy-2 issue - will this be moved to the new umbraco.deploy.issues repo, or do I need to start a new issue there?
