### ISSUE TITLE
Unable to transfer/restore content with empty blocks in a blocklist editor

### ISSUE THREAD

**Issue by HalldorLyngmo** [umbraco/Umbraco.Cloud.Issues#276]
I've just discovered that users might want to create empty blocks in the blocklist editor for some reason. This creates a problem when the content node is being transferred/restored between environments as Deploy / Deploy.Contrib expects there to be at least one property editor for that block. 

![image](https://user-images.githubusercontent.com/42831978/98367986-d93e6580-2036-11eb-9261-c751182ab602.png)

Reproduction
------------

1. Two environments.
2. Two document types: 
3. One enabled as Root node with a blocklist editor and one empty document type which is an element.
4. With the blocklist editor you pick the empty element
5. Then create a node and add the the empty block to the blocklist editor
6. Transfer or Restore it between the environements. 
7. End result: `System.NullReferenceException: Object reference not set to an instance of an object.`

### Bug summary

```
REMOTE:
System.NullReferenceException: Object reference not set to an instance of an object.

   at Umbraco.Deploy.Contrib.Connectors.ValueConnectors.BlockEditorValueConnector.ToArtifact(Object value, PropertyType propertyType, ICollection`1 dependencies) in C:\UmbracoRepos\Deploy-contrib-3\Umbraco.Deploy.Contrib\src\Umbraco.Deploy.Contrib.Connectors\ValueConnectors\BlockEditorValueConnector.cs:line 86
   at Umbraco.Deploy.Connectors.ServiceConnectors.ContentConnector.ContentConnectorBase`2.AddPropertyValue(ICollection`1 dependencies, Boolean published, PropertyValue propertyValue, IValueConnector valueConnector, Property property, IDictionary`2 propertyCollection)
   at Umbraco.Deploy.Connectors.ServiceConnectors.ContentConnector.ContentConnectorBase`2.AddProperty(Property property, ICollection`1 dependencies, Boolean published, IDictionary`2 propertyCollection)
   at Umbraco.Deploy.Connectors.ServiceConnectors.ContentConnector.ContentConnectorBase`2.MapArtifactProperties(PropertyCollection properties, ICollection`1 dependencies, Boolean published)
   at Umbraco.Deploy.Connectors.ServiceConnectors.ContentConnector.DocumentConnector.MapVersion(IContent content, ICollection`1 dependencies, Boolean published)
   at Umbraco.Deploy.Connectors.ServiceConnectors.ContentConnector.DocumentConnector.GetArtifact(GuidUdi udi, IContent content)
```

https://github.com/umbraco/Umbraco.Deploy.Contrib/blob/dev-v3/src/Umbraco.Deploy.Contrib.Connectors/ValueConnectors/BlockEditorValueConnector.cs#L86

The main issue is because we did not anticipate that there would be an empty block used like this. The Deploy.Contrib does not have a null check in place and therefore it fails when trying to access the properties which are expected to be there.

### Possible solution
Add a null check in two places before the foreach for the block properties and only do something if there are properties
`if (block.PropertyValues != null)
`

ToArtifact: 
https://github.com/umbraco/Umbraco.Deploy.Contrib/blob/dev-v3/src/Umbraco.Deploy.Contrib.Connectors/ValueConnectors/BlockEditorValueConnector.cs#L86

FromArtifact: 
https://github.com/umbraco/Umbraco.Deploy.Contrib/blob/dev-v3/src/Umbraco.Deploy.Contrib.Connectors/ValueConnectors/BlockEditorValueConnector.cs#L152

### Specifics

**Versions**
- Umbraco.Core.dll: 8.9.0
- Umbraco.Forms.Core.dll: 8.5.4
- Umbraco.Deploy.dll: 3.5.1
- Umbraco.Deploy.Contrib.Connectors.dll: 3.0.2

### Expected result
I expect the content to be transferred without any errors or at least get a more helpful exception message if this is not supported.

### Actual result
![image](https://user-images.githubusercontent.com/42831978/98368351-7e593e00-2037-11eb-84a0-2295478cdcb6.png)

---
_This item has been added to our backlog [AB#10603](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/10603)_

**Comment by nul800sebastiaan** [comment]
Thanks @HalldorLyngmo - we'll have to have a look!

**Comment by benq-z7** [comment]
Just wondering if there is an ETA on getting this fix merged and deployed? My team is currently stuck unable to push an entire site worth of content between environments due to this error.

**Comment by nul800sebastiaan** [comment]
We just merged the fix for this problem in PR https://github.com/umbraco/Umbraco.Deploy.Contrib/pull/46

This is now available on NuGet or from this zip file:

[UmbracoDeploy.Contrib.3.0.3.zip](https://github.com/umbraco/Umbraco.Cloud.Issues/files/6068538/UmbracoDeploy.Contrib.3.0.3.zip)

**Comment by prosperva** [comment]
Facing same issue installing UmbracoDeploy.Contrib package to v3.0.3,
