### ISSUE TITLE
Migration of LeBlender content in Umbraco 7

### ISSUE THREAD

**Issue by RachBreeze** [umbraco/Umbraco.Cloud.Issues#357]
This issue is similar to https://github.com/umbraco/Umbraco.Cloud.Issues/issues/191. We have the error message shown at the end of the post and have been working with André Søndergaard to resolve it id 59328, he has advised I raise it here as a ticket.

We have added "Umbraco.Deploy.Contrib.Connectors" to the project and have done some investigation. We believe that the issue may be related to a LeBlender editor using related links as detailed here https://our.umbraco.com/forum/umbraco-cloud/90751-pushing-related-links-content-on-a-leblender-grid-component-returns-error

`Unable to cast object of type 'Newtonsoft.Json.Linq.JObject' to type 'Newtonsoft.Json.Linq.JArray'.
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at Umbraco.Deploy.Contrib.Connectors.ValueConnectors.RelatedLinks2ValueConnector.GetValue(Property property, ICollection`1 dependencies)
   at Umbraco.Deploy.Contrib.Connectors.GridCellValueConnectors.LeBlenderGridCellValueConnector.GetValue(GridControl control, Property property, ICollection`1 dependencies)
   at Umbraco.Deploy.ValueConnectors.GridValueConnector.GetValue(Property property, ICollection`1 dependencies)
   at Umbraco.Deploy.ServiceConnectors.ContentConnectorBase`2.<>c__DisplayClass7_0.<MapProperties>b__1(Property x)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Umbraco.Deploy.ServiceConnectors.ContentConnectorBase`2.MapProperties(PropertyCollection properties, ICollection`1 dependencies)
   at Umbraco.Deploy.ServiceConnectors.DocumentConnector.MapVersion(IContent content, ICollection`1 dependencies)
   at Umbraco.Deploy.ServiceConnectors.DocumentConnector.GetArtifact(GuidUdi udi, IContent content)
   at Umbraco.Deploy.ServiceConnectors.DocumentConnector.GetArtifact(GuidUdi udi)
   at Umbraco.Deploy.ServiceConnectors.ServiceConnectorBase`3.Umbraco.Core.Deploy.IServiceConnector.GetArtifact(Udi udi)
   at Umbraco.Deploy.Environments.LocalUmbracoEnvironment.GetSignatures(IEnumerable`1 udis, CancellationToken token)
   at Umbraco.Deploy.Environments.LocalUmbracoEnvironment.CreateManifestAsync(Guid sessionId, IEnumerable`1 udis, IEnumerable`1 exclude, CancellationToken token)
   at Umbraco.Deploy.WorkItems.DeployRestoreWorkItemBase.<CreateManifestOnSource>d__12.MoveNext()`

**Comment by c9mbundy** [comment]
Sounds similar to [Umbraco.Deploy.Issues/issues/38](https://github.com/umbraco/Umbraco.Deploy.Issues/issues/38) where Deploy 2.1.x appears to fail parsing DocTypeGridEditor content if it contains array/list properties.
