### ISSUE TITLE
Deploy of block list fails if element doesn't contains custom properties

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Cloud.Issues#374]
Based on Umbraco 8.13.0 and Deploy 4.1.2 the tranfer fails if the block list editor contains element types where one or more of the used element types don't contain custom properties - so no settings and an element type without adding any custom properties to it.

In a specific use case I have a "Sidebar" composition with a Block List eidtor.

![image](https://user-images.githubusercontent.com/2919859/117692026-dcb8d200-b1bc-11eb-9fef-2c9ed53809ea.png)

![image](https://user-images.githubusercontent.com/2919859/117692071-ecd0b180-b1bc-11eb-83b4-ebef64f6d908.png)

**Block Latest News**

![image](https://user-images.githubusercontent.com/2919859/117692195-125dbb00-b1bd-11eb-931c-565936571087.png)

**Block  Quick Links**

![image](https://user-images.githubusercontent.com/2919859/117692322-33261080-b1bd-11eb-8a82-2e73db6ff700.png)

The Sidebar composition is used on two document types "Search" and "News Article".

When transferring the Search page, the transfer fails with the "Block Latest News" added.

![image](https://user-images.githubusercontent.com/2919859/117692570-708a9e00-b1bd-11eb-925d-0accbf112b81.png)

![image](https://user-images.githubusercontent.com/2919859/117692681-8e580300-b1bd-11eb-92d5-8bcd7749e237.png)

But when I remove "Block Latest News", hit "Save & Publish" and transfer content again, it works perfectly fine.

I get the same issue with "News Article", but works when removing the "Block Latest News". It seems to be an issue somewhere in BlockEditorValueConnector and looks like it doing a where clause on something that is null.

```
67913fd2 - Executing, 20% - Create manifest on source
67913fd2 - Executing, 25% - Review manifest on target
67913fd2 - Executing, 28% - Negotiate files transfer.
67913fd2 - Executing, 30% - Create package on source
67913fd2 - Executing, 80% - Exception!
67913fd2 - Executing, 80% - Abort remote session
67913fd2 - Failed, 80% - Total time 00:00:02.397.

-- EXCEPTION ---------------------------------------------------
 (proper exception traces at the end of this log)
System.NullReferenceException: Object reference not set to an instance of an object.
----------------------------------------------------------------

EXCEPTION:

System.NullReferenceException: Object reference not set to an instance of an object.
   at Umbraco.Deploy.Contrib.Connectors.ValueConnectors.BlockEditorValueConnector.ToArtifact(Object value, PropertyType propertyType, ICollection`1 dependencies)
   at Umbraco.Deploy.Connectors.ServiceConnectors.ContentConnector.ContentConnectorBase`2.SerializeNonVariantValue(ICollection`1 dependencies, IDictionary`2 propertyCollection, Property property, IValueConnector valueConnector)
   at Umbraco.Deploy.Connectors.ServiceConnectors.ContentConnector.ContentConnectorBase`2.MapArtifactProperties(PropertyCollection properties, ICollection`1 dependencies, Boolean published)
   at Umbraco.Deploy.Connectors.ServiceConnectors.ContentConnector.DocumentConnectorBase.MapVersion(IContent content, ICollection`1 dependencies, Boolean published)
   at Umbraco.Deploy.Connectors.ServiceConnectors.ContentConnector.DocumentConnector.GetArtifact(GuidUdi udi, IContent content)
   at Umbraco.Deploy.Connectors.ServiceConnectors.ContentConnector.DocumentConnector.GetArtifact(GuidUdi udi)
   at Umbraco.Deploy.Connectors.ServiceConnectors.ServiceConnectorBase`3.Umbraco.Core.Deploy.IServiceConnector.GetArtifact(Udi udi)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Umbraco.Deploy.Environments.CurrentEnvironment.CreatePackage(Guid sessionId, Manifest manifest)
   at Umbraco.Deploy.Environments.CurrentEnvironment.CreatePackageAsync(Guid sessionId, Manifest manifest, CancellationToken token)
   at Umbraco.Deploy.Work.WorkItems.DeployRestoreWorkItemBase.<CreatePackageOnSource>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.Work.WorkItems.SourceDeployWorkItem.<ProceedToPackage>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.Work.WorkItems.SourceDeployWorkItem.<ExecuteAsyncSub>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Umbraco.Deploy.Work.WorkItems.SourceDeployWorkItem.<ExecuteAsyncSub>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.Work.WorkItems.SourceDeployWorkItem.<ExecuteAsync>d__16.MoveNext()
```

**Comment by bjarnef** [comment]
@nul800sebastiaan ahh, I noticed you recently created an issue template specifically for Deploy here:
https://github.com/umbraco/Umbraco.Cloud.Issues/commit/448e19d0a0a6f300fd0e08e8009cb7d931c13752

and since this most likely is a bug in Deploy regarding `BlockEditorValueConnector` it should probably be moved to Deploy issue tracker. Could you transfer the issue or should I close this and submit a new one here?
https://github.com/umbraco/Umbraco.Deploy.Issues
