### ISSUE TITLE
Problems cloning with the UaaS.cmd tool

### ISSUE THREAD

**Issue by meyntony** [umbraco/Umbraco.Cloud.Issues#424]
### Issue description

Creating a new Umbraco cloud project initially gives me a project with the Git clone URL with the GUID
![image](https://user-images.githubusercontent.com/85172999/130159248-1005587f-916a-46e5-9cda-0f2c049ce8c6.png)

After a few minutes and refreshing the portal page: the Git clone URL changes to a human readable name

![image](https://user-images.githubusercontent.com/85172999/130159367-97cb2884-59a0-4f6d-8b32-4b209b650857.png)

Neither of these Git URLs seem to work with the UaaS Cli
https://our.umbraco.com/documentation/Umbraco-Cloud/Set-Up/Working-With-UaaS-Cli/

1.  With the GUID Git URL: The clone works fine but pushing local changes back does not seem to work.
2. With the Human readable Git URL: The clone seems to be broken with the following error
![image](https://user-images.githubusercontent.com/85172999/130159894-f2697341-c460-420d-8863-2aa47d667df9.png)

`Unhandled Exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Projects\CloudSites\Chat\TestMe.Web\web.config'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.OpenUrlDelegate(Object xmlResolver)
   at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
   at System.Threading.CompressedStack.Run(CompressedStack compressedStack, ContextCallback callback, Object state)
   at System.Xml.XmlTextReaderImpl.OpenUrl()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.Load(String filename)
   at Waasp.Program.GetUmbracoVersion(String solutionPath, String alias)
   at Waasp.Program.Main(String[] args)`

**Comment by c9mbundy** [comment]
Same problem encountered.

**Comment by sergiutesu** [comment]
Encountered the same problem as well.

**Comment by Frost117** [comment]
I manage to get this working by giving the namespace the same name as the git url. IE. if it is called /wagama.git then by giving the namespace then you will be able to get past the error.

**Comment by Frost117** [comment]
![image](https://user-images.githubusercontent.com/32164310/130199918-cfba5440-d212-4e1e-9705-18104a68f543.png)

**Comment by nul800sebastiaan** [comment]
Updated version:

```
@ECHO OFF
ECHO One second...
ECHO Downloading helper executable (Waasp.exe)
powershell -ExecutionPolicy Bypass -Command "(New-Object Net.WebClient).DownloadFile('https://umbracoreleases.blob.core.windows.net/download/Waasp.exe', 'Waasp.exe')"

SET /P url="Clone URL: " 
SET /P alias="Namespace: "

REM From https://stackoverflow.com/a/33155502/5018
for %%a in ("%url%") do (
   set "urlName=%%~NXa"
)
REM Remove `.git` suffix
SET identifier=%urlName:.git=%

IF NOT EXIST %alias%.Web (
	git clone %url%
)

IF EXIST %identifier% REN %identifier% %alias%.Web

Waasp.exe "%CD%" %alias% %url%
DEL Waasp.exe /Q
```

Please do a few tests but I tested it to work with an old GUID URL and a new named URL.

**Comment by c9mbundy** [comment]
@nul800sebastiaan - Yep, that works for me.

**Comment by nul800sebastiaan** [comment]
Thanks @c9mbundy - this version is now live, when downloading the file you'll get the latest version.
