### ISSUE TITLE
Keep alive failed - System.Threading.Tasks.TaskCanceledException

### ISSUE THREAD

**Issue by hfloyd** [umbraco/Umbraco.Cloud.Issues#466]
## Issue description

I keep getting these errors on the live site error log. I used an UmbracoSettings.config transform to set the proper domain name, so the error is not a localhost 404 (a common issue I've seen elsewhere).

```
Message:
Keep alive failed (at '"https://PROJECT.euwest01.umbraco.io/api/keepalive/ping"').
								
Exception:
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext()
```

## Versions
Umbraco Id
Umbraco 8.17.0
Deploy 4.3.0.0
Forms 8.8.0

**Comment by sajumb** [comment]
Thanks for the bug report. We have created a ticket in our backlog. We will consider it and try to reproduce the issue.

**Comment by c9mbundy** [comment]
Note - this solution does not work for v7 - as 'keepAlive' is apparently not a supported config settings element - so the site won't startup if you try to use this v8 solution, meaning that you can't configure the URL being requested for the keepAlive.

This might be resolvable on v7 using IIS Rewite if the requested URI for the task was something other than /umbraco - for more details see #533 - but at the moment I am logging a variety of HOST/URI combinations for the request, such as:

Failed (at "https://{custom-host}.:443/umbraco")  -- note the invalid .: 
Failed (at "https://{project}.euwest01.umbraco.io:443/umbraco")
Failed (at "https://{guid}.azurewebsites.net:443/umbraco")

**Comment by CarlSargunar** [comment]
I'm seeing a lot of these in my v8 cloud sites still - to confirm it's happening on Localhost URL for me

Keep alive failed (at '"https://localhost/umbraco/api/keepalive/ping"').

Exception : 
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: An attempt was made to access a socket in a way forbidden by its access permissions 127.0.0.1:443
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext()

**Comment by mclausen** [comment]
Hi there 🤠

It seems like this is quite an old issue, and to me, it sounds looks like, and quacks like a CMS Issue 🦆 😅. Independent of the Umbraco Cloud, I assume that the symptoms would occur on any IIS-hosted processes, and ties into how Umbraco is resolving the address.

I am going to close this issue, and if this still is a problem please create an issue on the [Umbraco CMS Tracker ](https://github.com/umbraco/Umbraco-CMS/issues).

Kind regards
@mclausen Cloud Platform/Core Teamlead
