### ISSUE TITLE
Local to dev form - The remote API has thrown an exception. It might have been caused by an inner System.Reflection.AmbiguousMatchException with message: Ambiguous match found.

### ISSUE THREAD

**Issue by Atchett** [umbraco/Umbraco.Cloud.Issues#521]
### Issue description

Hi,

I am posting this issue based on a support issue I have been trying to rsolve with the web chat support team.

I am receiving the error:

The remote API has thrown an exception. It might have been caused by an inner System.Reflection.AmbiguousMatchException with message: Ambiguous match found.

when trying to deploy a form from my local environment to dev (cloud).

Umbraco Version: 8.17.0
Deploy Version: 4.4.0 (just upgraded)
Forms Version: 8.10.0 (just upgraded)

Note, I upgraded the development environment on the portal and then pulled the changed down. I did this before creating any forms.

A bit of background and steps taken to create / deploy the form:

I am working in **local**, then deploy to dev, check and deploy to live. This is not a fully live site yet, just in dev.

1) 2 x Forms created in local, fairly simple forms no pages or conditions etc
2) Create submit page doc type and 2 submit pages and the form theme
3) added the pages created in step 2 to the form workflows so that they are the landing pages when the forms are submitted and added the forms to the required page templates
4) Attempted to deploy the content to dev, but got the error that they needed the forms
5) Tried to deploy the forms to dev but got the error above
6) Contacted support

In the meantime:

7) I deleted the forms and deleted all references to the forms in the page templates
8) Saved all the templates / doc types relevant to the forms
9) pushed the changes to dev
10) Deployed the content to dev (all working)
11) Content / DocTypes created in step 2 all visible on dev so deployed to live, again all working

12) Created a single, 3 field form, did not add to any pages or reference it anywhere
13) Attempted to deploy the form to dev and got the same error

Now stuck, but I can deploy content / media files still.

Full error message - 

8fe56799 - Executing, 10% - Get remote session
8fe56799 - Executing, 20% - Create manifest on source
8fe56799 - Executing, 25% - Review manifest on target
8fe56799 - Executing, 28% - Negotiate files transfer.
8fe56799 - Executing, 30% - Create package on source
8fe56799 - Executing, 32% - Transfer 0 files.
8fe56799 - Executing, 32% - Complete local session
8fe56799 - Executing, 35% - Process package on target
8fe56799 - Executing, 80% - Exception!
8fe56799 - Executing, 80% - Abort remote session
8fe56799 - Failed, 80% - Total time 00:00:02.249.

-- EXCEPTION ---------------------------------------------------
 (proper exception traces at the end of this log)
System.Reflection.AmbiguousMatchException: Ambiguous match found.
Umbraco.Deploy.Exceptions.ProcessArtifactException: Process pass #9 failed for artifact umb://forms-form/cd70a7c3b6ab4fc09267945a2811dfcd.
 On: <umb://forms-form/cd70a7c3b6ab4fc09267945a2811dfcd>
Umbraco.Deploy.Exceptions.RemoteApiException: The remote API has thrown an exception.
-- UDIS --------------------------------------------------------
<umb://forms-form/cd70a7c3b6ab4fc09267945a2811dfcd>
----------------------------------------------------------------

EXCEPTION:

Umbraco.Deploy.Exceptions.RemoteApiException: The remote API has thrown an exception.
   at Umbraco.Deploy.Environments.RemoteUmbracoEnvironment.<SucceedOrThrow>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.Environments.RemoteUmbracoEnvironment.<WaitAction>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.Environments.RemoteUmbracoEnvironment.<ProcessPackageAsync>d__43.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.Work.WorkItems.DeployRestoreWorkItemBase.<ProcessPackage>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.Work.WorkItems.SourceDeployWorkItem.<ExecuteAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Umbraco.Deploy.Work.WorkItems.SourceDeployWorkItem.<ExecuteAsync>d__16.MoveNext()

REMOTE:
Umbraco.Deploy.Exceptions.ProcessArtifactException: Process pass #9 failed for artifact umb://forms-form/cd70a7c3b6ab4fc09267945a2811dfcd.

   at Umbraco.Deploy.Environments.CurrentEnvironment.ProcessArtifacts(IEnumerable`1 arts, IDeployContext context, CancellationToken token)
   at Umbraco.Deploy.Environments.CurrentEnvironment.ProcessPackageAsync(Guid sessionId, Package package, CancellationToken token)
   at Umbraco.Deploy.Environments.EnvironmentController.<>c__DisplayClass14_0.<<BeginProcessPackage>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Umbraco.Deploy.Work.WorkItems.SessionWorkItem.<ExecuteAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Umbraco.Deploy.Work.WorkItems.SessionWorkItem.WaitIdle()
   at Umbraco.Deploy.Environments.EnvironmentController.WaitIdle(SessionActionModel model)
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_2.<GetExecutor>b__2(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext()
--> System.Reflection.AmbiguousMatchException: Ambiguous match found.

   at System.RuntimeType.GetMethodImpl(String name, BindingFlags bindingAttr, Binder binder, CallingConventions callConv, Type[] types, ParameterModifier[] modifiers)
   at System.Type.GetMethod(String name, BindingFlags bindingAttr)
   at Umbraco.Deploy.Core.ReflectionUtility.GetMethodInfo(Type type, String methodName, Func`2 filter)
   at Umbraco.Deploy.Core.ReflectionUtility.CallMethod(Object obj, String methodName, Object[] parameters)
   at Umbraco.Deploy.Forms.UmbracoFormsCompatibility.InsertViaVersionCompatiblity(IFormService service, Form item)
   at Umbraco.Deploy.Forms.ServiceConnectors.FormConnector.Pass9(ArtifactDeployState`2 state, IDeployContext context)
   at Umbraco.Deploy.Forms.ServiceConnectors.FormConnector.Process(ArtifactDeployState`2 state, IDeployContext context, Int32 pass)
   at Umbraco.Deploy.Environments.CurrentEnvironment.ProcessArtifacts(IEnumerable`1 arts, IDeployContext context, CancellationToken token)

**Comment by AndyButland** [comment]
Thanks for reporting this along with the detailed information.  I've found the issue - unfortunately Forms 10.0 has introduced an overload on a method used by Deploy for form deployment, which has led to this "Ambiguous match found".  To fix we'll need to update Deploy to be more specific in it's method selection for this operation.

This will be available in version 4.4.3 of Deploy, which on normal release schedules we expect to have out on 25th January.

I'll speak with the support team too such that they have a patch available if you or others with the same issue need the resolution sooner.
