### ISSUE TITLE
Keep Alive triggering errors

### ISSUE THREAD

**Issue by c9mbundy** [umbraco/Umbraco.Cloud.Issues#533]
### Issue description

It's a bit inconsistent, but I am getting errors logged of the form:
									
```
Message:
Failed (at "https://www.mydomainname.com.:443/umbraco").
									
Exception:
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext()
```
I guess that the dot at the end of the domain - before the :443 - being the possible candidate.

When this happens it logs this error at 5min intervals.

**Comment by sajumb** [comment]
Thanks for the bug report. We have created a ticket in our backlog. We will consider the issue and try to reproduce the issue.

**Comment by RyuLindow** [comment]
Already reported here https://github.com/umbraco/Umbraco.Cloud.Issues/issues/466

**Comment by sajumb** [comment]
As #466 already addressed the same issue we are closing this issue here and will proceed with #466 exclusively.

**Comment by c9mbundy** [comment]
@sajumb - Unfortunately #466 does not appear to resolve my situation

My case involves multiple v7 sites running on Umbraco-Cloud which are logging errors with the keepAlive service task.

Requesting a keepAlive URL that is ignored is one thing, but when the URL requested is simply invalid syntax, it results in an error being logged every 5mins - and it's not uncommon to have the log filling up with 1000's of these - and the portal keeps accumulating all errors, so you need to clear them all on a regular basis - which means you don't get to see useful errors.

The keepAlive appears to be scheduled by Umbraco.Deploy, and the v7 version does that the same as with v8.

However, the problem appears to be that by default v7 does not know how to specify the request for that URL.

In v8+ there is the ability to configure the URL for the keepAlive request, but in v7 there appears to be no support for that.

If you try to configure the keepAlive route on v7 to match the solution used for #466, the site will fail to startup because an unsupported settings element 'keepAlive' was specified.

When I checked the v7 versions of Umbraco.Core and Umbraco.Web there is no code dealing with 'keepAlive' whereas in the v8 versions there is a heap of code for it.

Presumably adding support for configuring keepAlive in v7 is undesirable, and unlikely to happen. 

However, if the requested URI for the task was either the correct '/api/keepalive/ping' or at least something unique, then it may be possible to resolve by using IIS Rewrite to intercept and rewrite the URL to mimic #466 - but the problem is that at the moment is that by default the requested URI is '/umbraco' - which is not something you can re-write.

**Comment by jemayn** [comment]
Thank you for reporting this. We're closing this issue as part of a cleanup of older items on the tracker. If you're still experiencing this problem on a current version of Umbraco Cloud, please open a new issue and we'll investigate.
