### ISSUE TITLE
Deploy wants to extract css file even though it doesn't exists.

### ISSUE THREAD

**Issue by Frost117** [umbraco/Umbraco.Cloud.Issues#534]
### Issue description

With Heartcore, the CSS stylesheets that are made using the RTE datatype, those datatypes are stored in the Block Container of each Heartcore project.

For some odd reason, the deployment is trying to extract a css file from the project. Here is the failure message:

```
2022-01-18 12:00:19.328 +00:00 [WRN] Unhandled exception 1 while handling message with ID 381e982e-2ea3-4935-8078-0bcfb1648133
System.InvalidOperationException: Copy failed from Www folder to repository failed. 'C:\home\site\wwwroot\css/RichTextStyles.css' did not exists
   at Umbraco.Cloud.Deployment.SiteExtension.Infrastructure.IO.Copy.CopyFileFromWwwRootToRepository.EnsureSourcePath(String relativeFilePath)
   at Umbraco.Cloud.Deployment.SiteExtension.Infrastructure.IO.Copy.CopyFileFromWwwRootToRepository.Copy(String relativeFilePath, Boolean overwrite)
   at Umbraco.Cloud.Deployment.SiteExtension.Handlers.ApplyChangesFromWwwRootToRepository.ApplyChangesFromWwwRootToRepositoryCommandHandler.Handle(ApplyChangesFromWwwRootToRepositoryCommand message)
   at Rebus.Pipeline.Receive.HandlerInvoker`1.<Invoke>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Rebus.Pipeline.Receive.DispatchIncomingMessageStep.<Process>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Sagas.LoadSagaDataStep.<Process>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Pipeline.Receive.ActivateHandlersStep.<Process>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Pipeline.Receive.HandleRoutingSlipsStep.<Process>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Pipeline.Receive.DeserializeIncomingMessageStep.<Process>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.DataBus.ClaimCheck.HydrateIncomingMessageStep.<Process>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Pipeline.Receive.HandleDeferredMessagesStep.<Process>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Retry.FailFast.FailFastStep.<Process>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Retry.Simple.SimpleRetryStrategyStep.<DispatchWithTrackerIdentifier>d__10.MoveNext()
```

**Comment by sitereactor** [comment]
Fix is expected to be rolled out on Tuesday Feb. 15th
