### ISSUE TITLE
Invalid response when starting deploy at target siteextension on base url 'https://{project-name}.scm.euwest01.umbraco.io/', task Id: '00000000-0000-0000-0000-000000000000''

### ISSUE THREAD

**Issue by HalldorLyngmo** [umbraco/Umbraco.Cloud.Issues#632]
### What is the issue
Rewrites are able to interfere with the deployment process so the deployment extraction is not started on the target environment. 
The end result is a failed deployment and the user needs to extract the changes manually from the Deployment dashboard in the backoffice of Umbraco.

![image](https://user-images.githubusercontent.com/42831978/214237211-1741c7e2-e4ba-4287-89a8-a8aa1a36d495.png)

## How to reproduce
I used a project with these versions 

- Umbraco 10.3.2
- Forms 10.2.2
- Deploy 10.1.2

**Site Extensions**

- Umbraco Cloud Deployment Site Extension - v0.1.679 and v0.1.746
- Umbraco Cloud Deployment Core Artifacts Site Extension - v1.0.16 and v1.0.18-beta

### Steps
Add rewrites to redirect everything except the default Umbraco URL to 'www'

1.
Add the IIS URL rewriter in the **Startup.cs** before `app.UseUmbraco...`
```
app.UseRewriter(new RewriteOptions().AddIISUrlRewrite(env.ContentRootFileProvider, "rewrites.xml"));
```
2.
Create `rewrites.xml` file in the root folder of the project
```
<?xml version="1.0" encoding="utf-8" ?>
<rewrite>
  <rules>
    <rule name="Redirect to www prefix" stopProcessing="true">
      <match url="(.*)" />
      <conditions>
        <add input="{HTTP_HOST}" pattern="^www\." negate="true" />
        <add input="{HTTP_HOST}" pattern="^localhost(:[0-9]+)?$" negate="true" />
        <add input="{HTTP_HOST}" pattern="\.umbraco\.io$" negate="true" />
      </conditions>
      <action type="Redirect" url="https://www.{HTTP_HOST}/{R:0}" />
    </rule>
  </rules>
</rewrite>
```
3.
Make sure the file is copied over during the build process by adding it to the `UmbracoProject.csproj` for the solution
```
  <ItemGroup>
    <Content Include="rewrites.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
```
4.
Create a document type and deploy the UDA file from f.ex. the Development environment to Live
The end result will be a failed deployment with the deployment log from below.

```
ACTIVITY LOG:
Deployment started
Fetching environment information, and preparing deployment
Preparing deployment on the source environment
Transferring data
Starting git push
Git: Pack data: Counting (1/0) 0 bytes
Git: Pack data: Deltafying (8/8) 0 bytes
Git: Transfer data: Transfer (8/8) 1793 bytes
Git push completed
Processing Umbraco data
Waiting for Umbraco data extraction for destination environment
Failed to start umbraco deploy extraction with error 'Invalid response when starting deploy at target site extension on base url 'https://hly-v10.scm.euwest01.umbraco.io/', task Id: '00000000-0000-0000-0000-000000000000'' and exception ''
Umbraco data extraction failed
```

## Clues
In the logs for the `UmbracoCloudDeploymentSiteExtension` on the target env. there will be an exception that shows the Azure website URL with a 'www' prefix. 

```
2023-01-24 07:37:10.822 +00:00 [ERR] Failed to make Deploy at target
System.Net.WebException: The remote name could not be resolved: 'www.cb35dfba-7d5b-40a3-aef3-9b00d6fd0375.azurewebsites.net'
   at RestSharp.RestClientExtensions.ThrowIfError(IRestResponse response)
   at RestSharp.RestClientExtensions.<PostAsync>d__25`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Cloud.Deployment.SiteExtension.Infrastructure.Deployment.Kudu.UmbracoDeployService.<>c__DisplayClass8_1.<<Deploy>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Polly.AsyncPolicy.<>c__DisplayClass40_0.<<ImplementationAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Polly.Retry.AsyncRetryEngine.<ImplementationAsync>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Polly.AsyncPolicy.<ExecuteAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Cloud.Deployment.SiteExtension.Infrastructure.Deployment.Kudu.UmbracoDeployService.<Deploy>d__8.MoveNext()
```

## Workaround
Add a negate for the Azure website URL's to the rewrite.
```
<add input="{HTTP_HOST}" negate="true" pattern=".*azurewebsites.net*" ignoreCase="true" />
```

**Comment by RobertCopilau** [comment]
Hey @HalldorLyngmo, we have reached the conclusion that the fix for this particular issue would be to update the documentation to mention the `<add input="{HTTP_HOST}" negate="true" pattern=".*azurewebsites.net*" ignoreCase="true" />` condition.

We would rather not hijack the rewrites that our users create in order to go around the issue. We will instead mention that in order for the `www` redirect to work correctly, an additional condition needs to be added in the rule.

Here are the PRs I mentioned:
https://github.com/umbraco/UmbracoDocs/pull/4955
https://github.com/umbraco/UmbracoDocs/pull/4958
