### ISSUE TITLE
V13: Saving relationtypes causes schema mismatch

### ISSUE THREAD

**Issue by Frost117** [umbraco/Umbraco.Cloud.Issues#723]
### Issue description

Had a project recently that was getting Schema mismatches when you worked on it locally.

It seemed odd to me, that when you span up the project locally it would reference a new ID of the uda file and not use what already is there. For reference here is what we get as the trace:
```
EXCEPTION
Umbraco.Deploy.Core.Exceptions.ProcessArtifactException: ProcessInit failed for artifact umb://relation-type/0976ae88838d41b89615867a146ab68c.
 ---> Umbraco.Deploy.Infrastructure.Exceptions.ArtifactCollisionException: Some artifacts collide on unique identifiers.
This means that they have different Udis, yet
they refer to the same unique Umbraco object
and therefore cannot be processed.
---------------------------------------------
Collisions for entity type "relation-type": 
  Collisions for unique identifier "umbForm":
    Artifact: umb://relation-type/0976ae88838d41b89615867a146ab68c
    {RelationType umb://relation-type/55faecb45ced4823a953cb9a202a813f}

   at Umbraco.Deploy.Infrastructure.Connectors.ServiceConnectors.RelationTypeConnector.ProcessInit(RelationTypeArtifact art, IDeployContext context)
   at Umbraco.Deploy.Infrastructure.Connectors.ServiceConnectors.ServiceConnectorBase`3.ProcessInit(IArtifact art, IDeployContext context)
   at Umbraco.Deploy.Infrastructure.Environments.CurrentEnvironment.<>c__DisplayClass40_0.<ProcessArtifacts>b__2(ArtifactWithOptions x)
   --- End of inner exception stack trace ---
   at Umbraco.Deploy.Infrastructure.Environments.CurrentEnvironment.<>c__DisplayClass40_0.<ProcessArtifacts>b__2(ArtifactWithOptions x)
   at System.Linq.Enumerable.WhereSelectListIterator`2.ToArray()
   at Umbraco.Deploy.Infrastructure.Environments.CurrentEnvironment.ProcessArtifacts(IEnumerable`1 arts, String ownerEmail, IDeployContext context, CancellationToken token)
   at Umbraco.Deploy.Infrastructure.Environments.CurrentEnvironment.ProcessPackageAsync(Guid sessionId, Package package, CancellationToken token)
   at Umbraco.Deploy.Infrastructure.Work.WorkItems.DiskReadWorkItem.Proceed(List`1 artifacts, Manifest manifest)
   at Umbraco.Deploy.Infrastructure.Work.WorkItems.DiskReadWorkItem.ExecuteAsyncSub(IWorkContext context, List`1 resume, CancellationToken token)
   at Umbraco.Deploy.Infrastructure.Work.WorkItems.DiskReadWorkItem.ExecuteAsync(IWorkContext context, CancellationToken token)
```

So I have reproduced the issue by doing the following:

1. Create new project on Umbraco Cloud.
2. When project had been created, log into the backoffice and save the Relation Type "Relate Form"
3. Clone the project down to your local machine.
4. Spin up the project.
5. When site begins local extraction you'll hit this issue.

**Comment by AndyButland** [comment]
This should be fixed with the next Forms patch that we are preparing and expect to have auto-upgraded on Cloud from 16th January.  In fixing something related I realised we weren't setting the GUID for the relation type when it's created when Forms migrates to the latest version.  Hence it would get created with a different GUID in different environments.

With the next update we'll be setting the GUID so it shouldn't occur moving forward.

To fix once you are on this situation, it's probably easiest to do a database update in one or both of your environments to set it to the appropriate GUID, via:

```
update umbracoRelationType
set typeUniqueId = 'BE98A22D-D0F8-4615-B2E4-1AAE86BF89BE'
where alias = 'umbForm'
```

And then re-save the relation type via the back-office to ensure the `.uda` file and signatures are updated.

**Comment by mclausen** [comment]
Howdy Folks,
Looks like a lot of water has flowed under the bridge since the last update on this issue.

Since there haven't been any updates since for a while and a solution was proposed by @AndyButland, then I am going to assume that this one has been fixed - If not please reopen the issue

Kind regards
@mclausen
