### ISSUE TITLE
Updating an SVG file in the media section causes an error when transferring to another environment

### ISSUE THREAD

**Issue by UEDevs** [umbraco/Umbraco.Cloud.Issues#8]
If you have an SVG file that exists on multiple environments, say the dev and live environments, it is not possible to update it on dev and sync to live as the file is locked.

Reproduction
------------

### Bug summary

An error is thrown when trying to transfer updates to existing SVG files.

### Specifics

This has been noticed with Umbraco versions 7.10.4 and 7.11.1. It also only seems to affect SVG files as we've managed to successfully edit JPG and ICO files without any errors.

### Steps to reproduce

1. (Allow SVG files to be uploaded to the media section in the umbracoSettings.config)
1. Add an SVG file to the media section on the dev environment.
1. Transfer the SVG file to the live environment.
1. Update the SVG file on the dev environment by browsing to it in the media section, using the file browser to pick the SVG file from your machine and save the media item.
1. Queue the SVG file for transfer.
1. Try to send the changes to the live environment.

### Expected result

The file should be sent successfully.

### Actual result

The source environment throws an error because it cannot access the file: `The process cannot access the file '<full_path_to_file.svg>' because it is being used by another process.`

Full error details:
```
b7c7a758 - Executing, 10% - Get remote session
b7c7a758 - Executing, 20% - Create manifest on source
b7c7a758 - Executing, 25% - Review manifest on target
b7c7a758 - Executing, 28% - Negotiate files transfer.
b7c7a758 - Executing, 30% - Create package on source
b7c7a758 - Executing, 32% - Transfer 1 file.
b7c7a758 - Executing, 32% - Complete local session
b7c7a758 - Executing, 35% - Process package on target
b7c7a758 - Executing, 80% - Complete remote session
b7c7a758 - Executing, 80% - Exception!
b7c7a758 - Executing, 80% - Abort remote session
b7c7a758 - Failed, 80% - Total time 00:00:02.715.

-- EXCEPTION ---------------------------------------------------
 (proper exception traces at the end of this log)
System.IO.IOException: The process cannot access the file 'C:\inetpub\temp\DWASFiles\Sites\991d8ef0-04dd-48f9-b660-78dd93418be6\VirtualDirectory0\site\wwwroot\media\1071\download.svg' because it is being used by another process.
System.Exception: Could not save file "1071/download.svg".
System.AggregateException: Failed to apply all changes (see exceptions).
System.AggregateException: Failed to apply all changes (see exceptions).
Umbraco.Deploy.Exceptions.RemoteApiException: The remote API has thrown an exception.
----------------------------------------------------------------

EXCEPTION:

Umbraco.Deploy.Exceptions.RemoteApiException: The remote API has thrown an exception.
   at Umbraco.Deploy.Environments.RemoteUmbracoEnvironment.<SucceedOrThrow>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.Environments.RemoteUmbracoEnvironment.<WaitAction>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.Environments.RemoteUmbracoEnvironment.<CompleteSessionAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.WorkItems.DeployRestoreWorkItemBase.<CloseSessionOn>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.WorkItems.SourceDeployWorkItem.<ExecuteAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Umbraco.Deploy.WorkItems.SourceDeployWorkItem.<ExecuteAsync>d__15.MoveNext()

REMOTE:
System.AggregateException: Failed to apply all changes (see exceptions).

   at Umbraco.Core.IO.ShadowFileSystems.Dispose()
   at Umbraco.Core.Scoping.Scope.<>c__DisplayClass70_0.<RobustExit>b__0()
   at Umbraco.Core.Scoping.Scope.TryFinally(Int32 index, Action[] actions)
   at Umbraco.Core.Scoping.Scope.RobustExit(Boolean completed, Boolean onException)
   at Umbraco.Core.Scoping.Scope.DisposeLastScope()
   at Umbraco.Core.Scoping.Scope.Dispose()
   at Umbraco.Deploy.WorkItems.SessionWorkItem.<>c__DisplayClass23_0.<Complete>b__0()
   at Umbraco.Deploy.Work.WorkTask.TryDo(Action action)
   at Umbraco.Deploy.Work.WorkContext.TryDo(Action action)
   at Umbraco.Deploy.WorkItems.SessionWorkItem.Complete(Boolean success)
   at Umbraco.Deploy.WorkItems.SessionWorkItem.<ExecuteCompleteAction>b__22_0()
--- End of stack trace from previous location where exception was thrown ---
   at Umbraco.Deploy.WorkItems.SessionWorkItem.WaitIdle()
   at Umbraco.Deploy.Environments.EnvironmentController.WaitCompleted(SessionActionModel model)
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
--> System.AggregateException: Failed to apply all changes (see exceptions).

   at Umbraco.Core.IO.ShadowFileSystem.Complete()
   at Umbraco.Core.IO.ShadowWrapper.UnShadow(Boolean complete)
   at Umbraco.Core.IO.ShadowFileSystems.Dispose()
--> System.Exception: Could not save file "1071/download.svg".


--> System.IO.IOException: The process cannot access the file 'C:\inetpub\temp\DWASFiles\Sites\991d8ef0-04dd-48f9-b660-78dd93418be6\VirtualDirectory0\site\wwwroot\media\1071\download.svg' because it is being used by another process.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at Umbraco.Core.IO.PhysicalFileSystem.<>c__DisplayClass24_0.<AddFile>b__0()
   at Umbraco.Core.IO.PhysicalFileSystem.WithRetry(Action action)
   at Umbraco.Core.IO.PhysicalFileSystem.AddFile(String path, String physicalPath, Boolean overrideIfExists, Boolean copy)
   at Umbraco.Core.IO.ShadowFileSystem.Complete()
```

**Comment by nul800sebastiaan** [comment]
Hi @UEDevs - Thanks for the report! Unfortunately I can't reproduce this at the moment, so hopefully it was just a fluke. 

If you have more info on how to reproduce then let us know!
